"""empty message

Revision ID: 9a96d15becdc
Revises: 
Create Date: 2018-07-17 22:47:07.736054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a96d15becdc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('companyname', sa.String(length=100), nullable=True),
    sa.Column('companydescription', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('contact', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('freelancer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=100), nullable=True),
    sa.Column('lastname', sa.String(length=50), nullable=True),
    sa.Column('contact', sa.String(length=50), nullable=True),
    sa.Column('skills', sa.String(length=500), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('password', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employer_id', sa.Integer(), nullable=False),
    sa.Column('freelancer_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=100), nullable=True),
    sa.Column('doc', sa.DateTime(), nullable=True),
    sa.Column('toc', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employer_id'], ['employer.id'], ),
    sa.ForeignKeyConstraint(['freelancer_id'], ['freelancer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_allocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employer_id', sa.Integer(), nullable=False),
    sa.Column('freelancer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employer_id'], ['employer.id'], ),
    sa.ForeignKeyConstraint(['freelancer_id'], ['freelancer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_postings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.Column('duration', sa.String(length=200), nullable=True),
    sa.Column('no_of_people', sa.Integer(), nullable=True),
    sa.Column('employer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employer_id'], ['employer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_postings')
    op.drop_table('job_allocation')
    op.drop_table('comments')
    op.drop_table('freelancer')
    op.drop_table('employer')
    # ### end Alembic commands ###
