"""empty message

Revision ID: e3cffb3e9ba7
Revises: 9a96d15becdc
Create Date: 2018-07-18 04:27:30.960037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3cffb3e9ba7'
down_revision = '9a96d15becdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'freelancer', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'freelancer', type_='unique')
    # ### end Alembic commands ###
